---
title: "Homework 10"
author: "Anthony Ferraro"
output: pdf_document
linkcolor: blue
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, fig.align = "center", out.width = "50%", warning = FALSE, message = FALSE)

library(tidyverse)
library(knitr)
library(forcats)

data("gss_cat")


theme_set(theme_minimal())
```


#### Combining the Levels of the "Marital" Variable
```{r}
marital_gss_cat = gss_cat %>% mutate(
  marital = fct_collapse(marital,
                         "Pre-Marriage" = c("Never married"),
                         "Marriage" = c("Married"),
                         "Post-Marriage" = c("Separated", "Divorced", "Widowed"),
                         "Missing" = c("No answer")
                         )
  ) 

knitr::kable(marital_gss_cat %>% 
  count(marital))
```

^[Question 1 Complete]



#### Making a Column of the Proportion of Responses in a Year for Each Marriage Level
```{r}
year_marital_counts = marital_gss_cat %>%
  count(year, marital)

prop_marital_status = year_marital_counts %>%
  group_by(year) %>%
  mutate(prop = n / sum(n))
```

^[Question 2 Complete]




#### Re-Ordering the Levels of Marriage Status
```{r}
ordered_prop_marital = prop_marital_status %>%
  mutate(marital = fct_reorder2(marital, year, prop))
```

^[Question 3 Complete]




